# Generated by Django 5.0.4 on 2024-04-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_products_manufactured_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='manufactured_at',
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
