# Generated by Django 5.0.4 on 2024-05-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_name_alter_products_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Счётчик просмотров'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание категории', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Введите название категории', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание продукта', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фото продукта', null=True, upload_to='catalog/photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(help_text='Введите название продукта', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите цену продукта', max_digits=10, verbose_name='Цена'),
        ),
    ]
