# Generated by Django 5.0.4 on 2024-05-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "блог", "verbose_name_plural": "блоги"},
        ),
        migrations.RemoveField(
            model_name="blog",
            name="view_count",
        ),
        migrations.AddField(
            model_name="blog",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="количество просмотров"
            ),
        ),
    ]
